/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import * as THREE from 'three';

/* interface GLTFResult extends GLTF {
	nodes: {
		Tree_6_0: THREE.Mesh
	}
	materials: Record<string, never>
	animations: THREE.AnimationClip[]
} */

type TreesModels = GLTF & {
	nodes: Record<string, THREE.Mesh>
	materials: {
		Colors: THREE.MeshStandardMaterial
	}
};

export const TreesModels = (props: JSX.IntrinsicElements['group']) => {
	const group = useRef(null!);
	const { nodes, materials } = useGLTF('models/low_poly_trees.glb') as TreesModels;
	// const { nodes, materials } = useGLTF('/models/low_poly_trees.gltf') as TreesModels;
	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={0.152}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Tree_6_0.geometry}
					material={nodes.Tree_6_0.material}
					position={[0, 0, 0.2]}
					scale={0.07}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Tree_5_0.geometry}
					material={materials.Colors}
					position={[1, 0.5, 0.2]}
					scale={0.07}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Tree_4_0.geometry}
					material={materials.Colors}
					position={[-0.9, 0.6, 0.2]}
					scale={0.06}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Tree_3_0.geometry}
					material={materials.Colors}
					position={[-0.5, -1, 1.2]}
					scale={0.3}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Tree_2_0.geometry}
					material={materials.Colors}
					position={[0.5, -1, 0.2]}
					rotation={[0, 0, 100 * Math.PI / 180]}
					scale={0.04}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Tree_1_0.geometry}
					material={materials.Colors}
					position={[1.7, -0.6, 0.2]}
					scale={0.06}
				/>
			</group>
		</group>
	);
};

useGLTF.preload('models/low_poly_trees.glb');
// useGLTF.preload('/models/low_poly_trees.gltf');
